shared:
    image: node:20
jobs:
    first:
        requires: [~pr, ~commit]
        steps: 
            - echo: echo first
    second:
        requires:
            - first
            - sd@12908:first
            - sd@12908:second
            - sd@12908:third
            - sd@12909:first
            - sd@12909:second
            - sd@12909:third
            - sd@12910:first
            - sd@12910:second
            - sd@12910:third
        steps:
            - echo: echo second
